name: sosmascota
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.2+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  provider: ^6.1.5
  smooth_page_indicator: ^1.2.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  path_provider: ^2.1.5
  path: ^1.9.1
  google_maps_flutter: ^2.12.2
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^17.1.2
  fl_chart: ^0.65.0
  intl: ^0.18.1
  geocoding: ^4.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/icono/sosmascota.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icono/sosmascota.png"