// Mocks generated by Mockito 5.4.6 from annotations
// in sos_mascotas/test/vista/auth/pantalla_registro_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:flutter/material.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:sos_mascotas/servicios/api_dni_servicio.dart' as _i3;
import 'package:sos_mascotas/vistamodelo/auth/registro_vm.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake
    implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_1 extends _i2.SmartFake
    implements _i1.TextEditingController {
  _FakeTextEditingController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiDniServicio_2 extends _i2.SmartFake
    implements _i3.ApiDniServicio {
  _FakeApiDniServicio_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RegistroVM].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistroVM extends _i2.Mock implements _i4.RegistroVM {
  MockRegistroVM() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.GlobalKey<_i1.FormState> get formKey =>
      (super.noSuchMethod(
            Invocation.getter(#formKey),
            returnValue: _FakeGlobalKey_0<_i1.FormState>(
              this,
              Invocation.getter(#formKey),
            ),
          )
          as _i1.GlobalKey<_i1.FormState>);

  @override
  _i1.TextEditingController get nombreCtrl =>
      (super.noSuchMethod(
            Invocation.getter(#nombreCtrl),
            returnValue: _FakeTextEditingController_1(
              this,
              Invocation.getter(#nombreCtrl),
            ),
          )
          as _i1.TextEditingController);

  @override
  _i1.TextEditingController get correoCtrl =>
      (super.noSuchMethod(
            Invocation.getter(#correoCtrl),
            returnValue: _FakeTextEditingController_1(
              this,
              Invocation.getter(#correoCtrl),
            ),
          )
          as _i1.TextEditingController);

  @override
  _i1.TextEditingController get telefonoCtrl =>
      (super.noSuchMethod(
            Invocation.getter(#telefonoCtrl),
            returnValue: _FakeTextEditingController_1(
              this,
              Invocation.getter(#telefonoCtrl),
            ),
          )
          as _i1.TextEditingController);

  @override
  _i1.TextEditingController get claveCtrl =>
      (super.noSuchMethod(
            Invocation.getter(#claveCtrl),
            returnValue: _FakeTextEditingController_1(
              this,
              Invocation.getter(#claveCtrl),
            ),
          )
          as _i1.TextEditingController);

  @override
  _i1.TextEditingController get dniCtrl =>
      (super.noSuchMethod(
            Invocation.getter(#dniCtrl),
            returnValue: _FakeTextEditingController_1(
              this,
              Invocation.getter(#dniCtrl),
            ),
          )
          as _i1.TextEditingController);

  @override
  bool get cargando =>
      (super.noSuchMethod(Invocation.getter(#cargando), returnValue: false)
          as bool);

  @override
  bool get buscandoDni =>
      (super.noSuchMethod(Invocation.getter(#buscandoDni), returnValue: false)
          as bool);

  @override
  _i3.ApiDniServicio get apiDni =>
      (super.noSuchMethod(
            Invocation.getter(#apiDni),
            returnValue: _FakeApiDniServicio_2(
              this,
              Invocation.getter(#apiDni),
            ),
          )
          as _i3.ApiDniServicio);

  @override
  set cargando(bool? value) => super.noSuchMethod(
    Invocation.setter(#cargando, value),
    returnValueForMissingStub: null,
  );

  @override
  set buscandoDni(bool? value) => super.noSuchMethod(
    Invocation.setter(#buscandoDni, value),
    returnValueForMissingStub: null,
  );

  @override
  set error(String? value) => super.noSuchMethod(
    Invocation.setter(#error, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> buscarYAutocompletarNombre() =>
      (super.noSuchMethod(
            Invocation.method(#buscarYAutocompletarNombre, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> registrarUsuario() =>
      (super.noSuchMethod(
            Invocation.method(#registrarUsuario, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
