// Mocks generated by Mockito 5.4.6 from annotations
// in sos_mascotas/test/vista/reportes/pantalla_avistamiento_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sos_mascotas/modelo/avistamiento.dart' as _i2;
import 'package:sos_mascotas/vistamodelo/reportes/avistamiento_vm.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAvistamiento_0 extends _i1.SmartFake implements _i2.Avistamiento {
  _FakeAvistamiento_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AvistamientoVM].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvistamientoVM extends _i1.Mock implements _i3.AvistamientoVM {
  MockAvistamientoVM() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Avistamiento get avistamiento =>
      (super.noSuchMethod(
            Invocation.getter(#avistamiento),
            returnValue: _FakeAvistamiento_0(
              this,
              Invocation.getter(#avistamiento),
            ),
          )
          as _i2.Avistamiento);

  @override
  _i3.EstadoCarga get estado =>
      (super.noSuchMethod(
            Invocation.getter(#estado),
            returnValue: _i3.EstadoCarga.inicial,
          )
          as _i3.EstadoCarga);

  @override
  bool get cargando =>
      (super.noSuchMethod(Invocation.getter(#cargando), returnValue: false)
          as bool);

  @override
  set avistamiento(_i2.Avistamiento? value) => super.noSuchMethod(
    Invocation.setter(#avistamiento, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setDireccion(String? v) => super.noSuchMethod(
    Invocation.method(#setDireccion, [v]),
    returnValueForMissingStub: null,
  );

  @override
  void setDescripcion(String? v) => super.noSuchMethod(
    Invocation.method(#setDescripcion, [v]),
    returnValueForMissingStub: null,
  );

  @override
  void limpiarMensaje() => super.noSuchMethod(
    Invocation.method(#limpiarMensaje, []),
    returnValueForMissingStub: null,
  );

  @override
  void actualizarUbicacion({
    required String? direccion,
    required String? distrito,
    required double? latitud,
    required double? longitud,
  }) => super.noSuchMethod(
    Invocation.method(#actualizarUbicacion, [], {
      #direccion: direccion,
      #distrito: distrito,
      #latitud: latitud,
      #longitud: longitud,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String?> subirFoto(_i5.File? archivo) =>
      (super.noSuchMethod(
            Invocation.method(#subirFoto, [archivo]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> guardarAvistamiento() =>
      (super.noSuchMethod(
            Invocation.method(#guardarAvistamiento, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
